fqdn: "github.com/kolo7/bench-tpl/output"
db:
  # dsn: "yc_mgchorus_rw:TPBDAhHMGchcBEtz@tcp(10.43.30.164:9001)/mgchorus?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  dsn: "root:E2FU0O1b@tcp(127.0.0.1:3306)/uni_comm?charset=utf8mb4&parseTime=True&loc=Local"
# epochConf:
#   barrage:
#     dir: "tpl"
#     epoch: 500
#   videos:
#     dir: "tpl"
#     epoch: 500
#   detail:
#     dir: "tpl"
#     epoch: 500
#   rank:
#     dir: "tpl"
#     epoch: 500
#   up:
#     dir: "tpl"
#     epoch: 500
#   share:
#     dir: "tpl"
#     epoch: 500
#   insert:
#     dir: "tpl"
#     epoch: 1000
#   insert-join:
#     dir: "tpl"
#     epoch: 500
#   insert-join-rel:
#     dir: "tpl"
#     epoch: 500
    
TableConf:
  sys_config:
    epoch: 1

